[project]
name = "advent-of-code"
version = "0.3.0"
description = "Submissions for advent of code"
authors = [
    {name = "Stefan Langenbach", email = "stefan@langenbach.online"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"

[dependency-groups]
dev = [
    "pytest-mock>=3.14.0",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "ty>=0.0.1a7",
    "ruff>=0.14.8",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "B",    # flake8-bugbear
    "BLE",  # flake8-blind-except
    "D",    # pydocstyle
    "DTZ",  # flake8-datetimez
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "PT",   # flake8-pytest-style
    "PTH",  # flake8-use-pathlib
    "S",    # flake8-bandit
    "UP",   # pyupgrade
]
ignore = ["D203", "D212", "D103"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["D104"]
"tests/*" = ["S101", "D100", "D103"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v --strict-markers --cov --cov-report=term"
markers = [
    "local: marks tests as running locally only (deselect with '-m \"not local\"')"
]
xfail_strict = true

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"
