from pathlib import Path

ROOT_PATH = Path(__file__).parent.parent
TEST_PATH = ROOT_PATH / "tests"
PACKAGE_PATH = ROOT_PATH / "advent_of_code"

TWENTY_TWENTY_TWO_PATH = PACKAGE_PATH / "twenty_twenty_two"
TWENTY_TWENTY_TWO_INPUT_PATH = TWENTY_TWENTY_TWO_PATH / "inputs"
TWENTY_TWENTY_TWO_TEST_PATH = TEST_PATH / "twenty_twenty_two"
TWENTY_TWENTY_TWO_TEST_INPUT_PATH = TWENTY_TWENTY_TWO_TEST_PATH / "inputs"

TWENTY_TWENTY_THREE_PATH = PACKAGE_PATH / "twenty_twenty_three"
TWENTY_TWENTY_THREE_INPUT_PATH = TWENTY_TWENTY_THREE_PATH / "inputs"
TWENTY_TWENTY_THREE_TEST_PATH = TEST_PATH / "twenty_twenty_three"
TWENTY_TWENTY_THREE_TEST_INPUT_PATH = TWENTY_TWENTY_THREE_TEST_PATH / "inputs"
